fragment HomePageParts on HomePage {
  __typename
  heroHeading
  heroSubtext
  heroCta
  featuresLabel
  featuresHeading
  featuresSubtext
  features {
    __typename
    icon
    title
    description
  }
  missionLabel
  missionHeading
  missionBody
  missionQuote
}

fragment WarumPageParts on WarumPage {
  __typename
  heroBadge
  heroHeading
  heroSubtext
  benefitsLabel
  benefitsHeading
  benefits {
    __typename
    icon
    title
    description
  }
  ctaLabel
  ctaHeading
  ctaBody
  ctaButtonLabel
}

fragment CrsvPageParts on CrsvPage {
  __typename
  heroHeading
  heroSubtext
  valuesIntro
  values {
    __typename
    icon
    title
    description
  }
  legalText
}

fragment KontaktPageParts on KontaktPage {
  __typename
  heroHeading
  heroBody
}

fragment DatenschutzPageParts on DatenschutzPage {
  __typename
  heroHeading
  heroSubtext
  sections {
    __typename
    heading
    body
  }
}

fragment ImpressumPageParts on ImpressumPage {
  __typename
  heroHeading
  heroSubtext
  sections {
    __typename
    heading
    body
  }
}

fragment StatutenPageParts on StatutenPage {
  __typename
  heroHeading
  heroSubtext
  pdfUrl
  pdfButtonLabel
  sections {
    __typename
    heading
    body
  }
  footerNote
}

fragment MembersDocParts on MembersDoc {
  __typename
  members {
    __typename
    name
    role
    location
    links {
      __typename
      type
      url
    }
  }
}
