//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homePage: HomePage;
  homePageConnection: HomePageConnection;
  warumPage: WarumPage;
  warumPageConnection: WarumPageConnection;
  crsvPage: CrsvPage;
  crsvPageConnection: CrsvPageConnection;
  kontaktPage: KontaktPage;
  kontaktPageConnection: KontaktPageConnection;
  datenschutzPage: DatenschutzPage;
  datenschutzPageConnection: DatenschutzPageConnection;
  impressumPage: ImpressumPage;
  impressumPageConnection: ImpressumPageConnection;
  statutenPage: StatutenPage;
  statutenPageConnection: StatutenPageConnection;
  membersDoc: MembersDoc;
  membersDocConnection: MembersDocConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
};


export type QueryWarumPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWarumPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WarumPageFilter>;
};


export type QueryCrsvPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCrsvPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CrsvPageFilter>;
};


export type QueryKontaktPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryKontaktPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KontaktPageFilter>;
};


export type QueryDatenschutzPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDatenschutzPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DatenschutzPageFilter>;
};


export type QueryImpressumPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryImpressumPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ImpressumPageFilter>;
};


export type QueryStatutenPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStatutenPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StatutenPageFilter>;
};


export type QueryMembersDocArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMembersDocConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MembersDocFilter>;
};

export type DocumentFilter = {
  homePage?: InputMaybe<HomePageFilter>;
  warumPage?: InputMaybe<WarumPageFilter>;
  crsvPage?: InputMaybe<CrsvPageFilter>;
  kontaktPage?: InputMaybe<KontaktPageFilter>;
  datenschutzPage?: InputMaybe<DatenschutzPageFilter>;
  impressumPage?: InputMaybe<ImpressumPageFilter>;
  statutenPage?: InputMaybe<StatutenPageFilter>;
  membersDoc?: InputMaybe<MembersDocFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = HomePage | WarumPage | CrsvPage | KontaktPage | DatenschutzPage | ImpressumPage | StatutenPage | MembersDoc | Folder;

export type HomePageFeatures = {
  __typename?: 'HomePageFeatures';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HomePage = Node & Document & {
  __typename?: 'HomePage';
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  heroCta?: Maybe<Scalars['String']['output']>;
  featuresLabel?: Maybe<Scalars['String']['output']>;
  featuresHeading?: Maybe<Scalars['String']['output']>;
  featuresSubtext?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<HomePageFeatures>>>;
  missionLabel?: Maybe<Scalars['String']['output']>;
  missionHeading?: Maybe<Scalars['String']['output']>;
  missionBody?: Maybe<Scalars['String']['output']>;
  missionQuote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomePageFeaturesFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomePageFilter = {
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  heroCta?: InputMaybe<StringFilter>;
  featuresLabel?: InputMaybe<StringFilter>;
  featuresHeading?: InputMaybe<StringFilter>;
  featuresSubtext?: InputMaybe<StringFilter>;
  features?: InputMaybe<HomePageFeaturesFilter>;
  missionLabel?: InputMaybe<StringFilter>;
  missionHeading?: InputMaybe<StringFilter>;
  missionBody?: InputMaybe<StringFilter>;
  missionQuote?: InputMaybe<StringFilter>;
};

export type HomePageConnectionEdges = {
  __typename?: 'HomePageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomePage>;
};

export type HomePageConnection = Connection & {
  __typename?: 'HomePageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomePageConnectionEdges>>>;
};

export type WarumPageBenefits = {
  __typename?: 'WarumPageBenefits';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type WarumPage = Node & Document & {
  __typename?: 'WarumPage';
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  benefitsLabel?: Maybe<Scalars['String']['output']>;
  benefitsHeading?: Maybe<Scalars['String']['output']>;
  benefits?: Maybe<Array<Maybe<WarumPageBenefits>>>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaBody?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WarumPageBenefitsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type WarumPageFilter = {
  heroBadge?: InputMaybe<StringFilter>;
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  benefitsLabel?: InputMaybe<StringFilter>;
  benefitsHeading?: InputMaybe<StringFilter>;
  benefits?: InputMaybe<WarumPageBenefitsFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaBody?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
};

export type WarumPageConnectionEdges = {
  __typename?: 'WarumPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<WarumPage>;
};

export type WarumPageConnection = Connection & {
  __typename?: 'WarumPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WarumPageConnectionEdges>>>;
};

export type CrsvPageValues = {
  __typename?: 'CrsvPageValues';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type CrsvPage = Node & Document & {
  __typename?: 'CrsvPage';
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  valuesIntro?: Maybe<Scalars['String']['output']>;
  values?: Maybe<Array<Maybe<CrsvPageValues>>>;
  legalText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CrsvPageValuesFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type CrsvPageFilter = {
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  valuesIntro?: InputMaybe<StringFilter>;
  values?: InputMaybe<CrsvPageValuesFilter>;
  legalText?: InputMaybe<StringFilter>;
};

export type CrsvPageConnectionEdges = {
  __typename?: 'CrsvPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CrsvPage>;
};

export type CrsvPageConnection = Connection & {
  __typename?: 'CrsvPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CrsvPageConnectionEdges>>>;
};

export type KontaktPage = Node & Document & {
  __typename?: 'KontaktPage';
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroBody?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type KontaktPageFilter = {
  heroHeading?: InputMaybe<StringFilter>;
  heroBody?: InputMaybe<StringFilter>;
};

export type KontaktPageConnectionEdges = {
  __typename?: 'KontaktPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<KontaktPage>;
};

export type KontaktPageConnection = Connection & {
  __typename?: 'KontaktPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<KontaktPageConnectionEdges>>>;
};

export type DatenschutzPageSections = {
  __typename?: 'DatenschutzPageSections';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type DatenschutzPage = Node & Document & {
  __typename?: 'DatenschutzPage';
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<DatenschutzPageSections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatenschutzPageSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type DatenschutzPageFilter = {
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  sections?: InputMaybe<DatenschutzPageSectionsFilter>;
};

export type DatenschutzPageConnectionEdges = {
  __typename?: 'DatenschutzPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DatenschutzPage>;
};

export type DatenschutzPageConnection = Connection & {
  __typename?: 'DatenschutzPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DatenschutzPageConnectionEdges>>>;
};

export type ImpressumPageSections = {
  __typename?: 'ImpressumPageSections';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type ImpressumPage = Node & Document & {
  __typename?: 'ImpressumPage';
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<ImpressumPageSections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImpressumPageSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type ImpressumPageFilter = {
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  sections?: InputMaybe<ImpressumPageSectionsFilter>;
};

export type ImpressumPageConnectionEdges = {
  __typename?: 'ImpressumPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ImpressumPage>;
};

export type ImpressumPageConnection = Connection & {
  __typename?: 'ImpressumPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ImpressumPageConnectionEdges>>>;
};

export type StatutenPageSections = {
  __typename?: 'StatutenPageSections';
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type StatutenPage = Node & Document & {
  __typename?: 'StatutenPage';
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  pdfUrl?: Maybe<Scalars['String']['output']>;
  pdfButtonLabel?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<StatutenPageSections>>>;
  footerNote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StatutenPageSectionsFilter = {
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type StatutenPageFilter = {
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  pdfUrl?: InputMaybe<StringFilter>;
  pdfButtonLabel?: InputMaybe<StringFilter>;
  sections?: InputMaybe<StatutenPageSectionsFilter>;
  footerNote?: InputMaybe<StringFilter>;
};

export type StatutenPageConnectionEdges = {
  __typename?: 'StatutenPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<StatutenPage>;
};

export type StatutenPageConnection = Connection & {
  __typename?: 'StatutenPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StatutenPageConnectionEdges>>>;
};

export type MembersDocMembersLinks = {
  __typename?: 'MembersDocMembersLinks';
  type?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type MembersDocMembers = {
  __typename?: 'MembersDocMembers';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<MembersDocMembersLinks>>>;
};

export type MembersDoc = Node & Document & {
  __typename?: 'MembersDoc';
  members?: Maybe<Array<Maybe<MembersDocMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MembersDocMembersLinksFilter = {
  type?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type MembersDocMembersFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  links?: InputMaybe<MembersDocMembersLinksFilter>;
};

export type MembersDocFilter = {
  members?: InputMaybe<MembersDocMembersFilter>;
};

export type MembersDocConnectionEdges = {
  __typename?: 'MembersDocConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<MembersDoc>;
};

export type MembersDocConnection = Connection & {
  __typename?: 'MembersDocConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MembersDocConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomePage: HomePage;
  createHomePage: HomePage;
  updateWarumPage: WarumPage;
  createWarumPage: WarumPage;
  updateCrsvPage: CrsvPage;
  createCrsvPage: CrsvPage;
  updateKontaktPage: KontaktPage;
  createKontaktPage: KontaktPage;
  updateDatenschutzPage: DatenschutzPage;
  createDatenschutzPage: DatenschutzPage;
  updateImpressumPage: ImpressumPage;
  createImpressumPage: ImpressumPage;
  updateStatutenPage: StatutenPage;
  createStatutenPage: StatutenPage;
  updateMembersDoc: MembersDoc;
  createMembersDoc: MembersDoc;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationCreateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationUpdateWarumPageArgs = {
  relativePath: Scalars['String']['input'];
  params: WarumPageMutation;
};


export type MutationCreateWarumPageArgs = {
  relativePath: Scalars['String']['input'];
  params: WarumPageMutation;
};


export type MutationUpdateCrsvPageArgs = {
  relativePath: Scalars['String']['input'];
  params: CrsvPageMutation;
};


export type MutationCreateCrsvPageArgs = {
  relativePath: Scalars['String']['input'];
  params: CrsvPageMutation;
};


export type MutationUpdateKontaktPageArgs = {
  relativePath: Scalars['String']['input'];
  params: KontaktPageMutation;
};


export type MutationCreateKontaktPageArgs = {
  relativePath: Scalars['String']['input'];
  params: KontaktPageMutation;
};


export type MutationUpdateDatenschutzPageArgs = {
  relativePath: Scalars['String']['input'];
  params: DatenschutzPageMutation;
};


export type MutationCreateDatenschutzPageArgs = {
  relativePath: Scalars['String']['input'];
  params: DatenschutzPageMutation;
};


export type MutationUpdateImpressumPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ImpressumPageMutation;
};


export type MutationCreateImpressumPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ImpressumPageMutation;
};


export type MutationUpdateStatutenPageArgs = {
  relativePath: Scalars['String']['input'];
  params: StatutenPageMutation;
};


export type MutationCreateStatutenPageArgs = {
  relativePath: Scalars['String']['input'];
  params: StatutenPageMutation;
};


export type MutationUpdateMembersDocArgs = {
  relativePath: Scalars['String']['input'];
  params: MembersDocMutation;
};


export type MutationCreateMembersDocArgs = {
  relativePath: Scalars['String']['input'];
  params: MembersDocMutation;
};

export type DocumentUpdateMutation = {
  homePage?: InputMaybe<HomePageMutation>;
  warumPage?: InputMaybe<WarumPageMutation>;
  crsvPage?: InputMaybe<CrsvPageMutation>;
  kontaktPage?: InputMaybe<KontaktPageMutation>;
  datenschutzPage?: InputMaybe<DatenschutzPageMutation>;
  impressumPage?: InputMaybe<ImpressumPageMutation>;
  statutenPage?: InputMaybe<StatutenPageMutation>;
  membersDoc?: InputMaybe<MembersDocMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homePage?: InputMaybe<HomePageMutation>;
  warumPage?: InputMaybe<WarumPageMutation>;
  crsvPage?: InputMaybe<CrsvPageMutation>;
  kontaktPage?: InputMaybe<KontaktPageMutation>;
  datenschutzPage?: InputMaybe<DatenschutzPageMutation>;
  impressumPage?: InputMaybe<ImpressumPageMutation>;
  statutenPage?: InputMaybe<StatutenPageMutation>;
  membersDoc?: InputMaybe<MembersDocMutation>;
};

export type HomePageFeaturesMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageMutation = {
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  heroCta?: InputMaybe<Scalars['String']['input']>;
  featuresLabel?: InputMaybe<Scalars['String']['input']>;
  featuresHeading?: InputMaybe<Scalars['String']['input']>;
  featuresSubtext?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<HomePageFeaturesMutation>>>;
  missionLabel?: InputMaybe<Scalars['String']['input']>;
  missionHeading?: InputMaybe<Scalars['String']['input']>;
  missionBody?: InputMaybe<Scalars['String']['input']>;
  missionQuote?: InputMaybe<Scalars['String']['input']>;
};

export type WarumPageBenefitsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type WarumPageMutation = {
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  benefitsLabel?: InputMaybe<Scalars['String']['input']>;
  benefitsHeading?: InputMaybe<Scalars['String']['input']>;
  benefits?: InputMaybe<Array<InputMaybe<WarumPageBenefitsMutation>>>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaBody?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
};

export type CrsvPageValuesMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type CrsvPageMutation = {
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  valuesIntro?: InputMaybe<Scalars['String']['input']>;
  values?: InputMaybe<Array<InputMaybe<CrsvPageValuesMutation>>>;
  legalText?: InputMaybe<Scalars['String']['input']>;
};

export type KontaktPageMutation = {
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroBody?: InputMaybe<Scalars['String']['input']>;
};

export type DatenschutzPageSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type DatenschutzPageMutation = {
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<DatenschutzPageSectionsMutation>>>;
};

export type ImpressumPageSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type ImpressumPageMutation = {
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<ImpressumPageSectionsMutation>>>;
};

export type StatutenPageSectionsMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type StatutenPageMutation = {
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  pdfUrl?: InputMaybe<Scalars['String']['input']>;
  pdfButtonLabel?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<StatutenPageSectionsMutation>>>;
  footerNote?: InputMaybe<Scalars['String']['input']>;
};

export type MembersDocMembersLinksMutation = {
  type?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type MembersDocMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<MembersDocMembersLinksMutation>>>;
};

export type MembersDocMutation = {
  members?: InputMaybe<Array<InputMaybe<MembersDocMembersMutation>>>;
};

export type HomePagePartsFragment = { __typename: 'HomePage', heroHeading?: string | null, heroSubtext?: string | null, heroCta?: string | null, featuresLabel?: string | null, featuresHeading?: string | null, featuresSubtext?: string | null, missionLabel?: string | null, missionHeading?: string | null, missionBody?: string | null, missionQuote?: string | null, features?: Array<{ __typename: 'HomePageFeatures', icon?: string | null, title?: string | null, description?: string | null } | null> | null };

export type WarumPagePartsFragment = { __typename: 'WarumPage', heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, benefitsLabel?: string | null, benefitsHeading?: string | null, ctaLabel?: string | null, ctaHeading?: string | null, ctaBody?: string | null, ctaButtonLabel?: string | null, benefits?: Array<{ __typename: 'WarumPageBenefits', icon?: string | null, title?: string | null, description?: string | null } | null> | null };

export type CrsvPagePartsFragment = { __typename: 'CrsvPage', heroHeading?: string | null, heroSubtext?: string | null, valuesIntro?: string | null, legalText?: string | null, values?: Array<{ __typename: 'CrsvPageValues', icon?: string | null, title?: string | null, description?: string | null } | null> | null };

export type KontaktPagePartsFragment = { __typename: 'KontaktPage', heroHeading?: string | null, heroBody?: string | null };

export type DatenschutzPagePartsFragment = { __typename: 'DatenschutzPage', heroHeading?: string | null, heroSubtext?: string | null, sections?: Array<{ __typename: 'DatenschutzPageSections', heading?: string | null, body?: string | null } | null> | null };

export type ImpressumPagePartsFragment = { __typename: 'ImpressumPage', heroHeading?: string | null, heroSubtext?: string | null, sections?: Array<{ __typename: 'ImpressumPageSections', heading?: string | null, body?: string | null } | null> | null };

export type StatutenPagePartsFragment = { __typename: 'StatutenPage', heroHeading?: string | null, heroSubtext?: string | null, pdfUrl?: string | null, pdfButtonLabel?: string | null, footerNote?: string | null, sections?: Array<{ __typename: 'StatutenPageSections', heading?: string | null, body?: string | null } | null> | null };

export type MembersDocPartsFragment = { __typename: 'MembersDoc', members?: Array<{ __typename: 'MembersDocMembers', name?: string | null, role?: string | null, location?: string | null, links?: Array<{ __typename: 'MembersDocMembersLinks', type?: string | null, url?: string | null } | null> | null } | null> | null };

export type HomePageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomePageQuery = { __typename?: 'Query', homePage: { __typename: 'HomePage', id: string, heroHeading?: string | null, heroSubtext?: string | null, heroCta?: string | null, featuresLabel?: string | null, featuresHeading?: string | null, featuresSubtext?: string | null, missionLabel?: string | null, missionHeading?: string | null, missionBody?: string | null, missionQuote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'HomePageFeatures', icon?: string | null, title?: string | null, description?: string | null } | null> | null } };

export type HomePageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
}>;


export type HomePageConnectionQuery = { __typename?: 'Query', homePageConnection: { __typename?: 'HomePageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomePageConnectionEdges', cursor: string, node?: { __typename: 'HomePage', id: string, heroHeading?: string | null, heroSubtext?: string | null, heroCta?: string | null, featuresLabel?: string | null, featuresHeading?: string | null, featuresSubtext?: string | null, missionLabel?: string | null, missionHeading?: string | null, missionBody?: string | null, missionQuote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'HomePageFeatures', icon?: string | null, title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type WarumPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WarumPageQuery = { __typename?: 'Query', warumPage: { __typename: 'WarumPage', id: string, heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, benefitsLabel?: string | null, benefitsHeading?: string | null, ctaLabel?: string | null, ctaHeading?: string | null, ctaBody?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, benefits?: Array<{ __typename: 'WarumPageBenefits', icon?: string | null, title?: string | null, description?: string | null } | null> | null } };

export type WarumPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WarumPageFilter>;
}>;


export type WarumPageConnectionQuery = { __typename?: 'Query', warumPageConnection: { __typename?: 'WarumPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WarumPageConnectionEdges', cursor: string, node?: { __typename: 'WarumPage', id: string, heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, benefitsLabel?: string | null, benefitsHeading?: string | null, ctaLabel?: string | null, ctaHeading?: string | null, ctaBody?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, benefits?: Array<{ __typename: 'WarumPageBenefits', icon?: string | null, title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type CrsvPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CrsvPageQuery = { __typename?: 'Query', crsvPage: { __typename: 'CrsvPage', id: string, heroHeading?: string | null, heroSubtext?: string | null, valuesIntro?: string | null, legalText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'CrsvPageValues', icon?: string | null, title?: string | null, description?: string | null } | null> | null } };

export type CrsvPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CrsvPageFilter>;
}>;


export type CrsvPageConnectionQuery = { __typename?: 'Query', crsvPageConnection: { __typename?: 'CrsvPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CrsvPageConnectionEdges', cursor: string, node?: { __typename: 'CrsvPage', id: string, heroHeading?: string | null, heroSubtext?: string | null, valuesIntro?: string | null, legalText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'CrsvPageValues', icon?: string | null, title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type KontaktPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type KontaktPageQuery = { __typename?: 'Query', kontaktPage: { __typename: 'KontaktPage', id: string, heroHeading?: string | null, heroBody?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type KontaktPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<KontaktPageFilter>;
}>;


export type KontaktPageConnectionQuery = { __typename?: 'Query', kontaktPageConnection: { __typename?: 'KontaktPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'KontaktPageConnectionEdges', cursor: string, node?: { __typename: 'KontaktPage', id: string, heroHeading?: string | null, heroBody?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DatenschutzPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DatenschutzPageQuery = { __typename?: 'Query', datenschutzPage: { __typename: 'DatenschutzPage', id: string, heroHeading?: string | null, heroSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'DatenschutzPageSections', heading?: string | null, body?: string | null } | null> | null } };

export type DatenschutzPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DatenschutzPageFilter>;
}>;


export type DatenschutzPageConnectionQuery = { __typename?: 'Query', datenschutzPageConnection: { __typename?: 'DatenschutzPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DatenschutzPageConnectionEdges', cursor: string, node?: { __typename: 'DatenschutzPage', id: string, heroHeading?: string | null, heroSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'DatenschutzPageSections', heading?: string | null, body?: string | null } | null> | null } | null } | null> | null } };

export type ImpressumPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ImpressumPageQuery = { __typename?: 'Query', impressumPage: { __typename: 'ImpressumPage', id: string, heroHeading?: string | null, heroSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'ImpressumPageSections', heading?: string | null, body?: string | null } | null> | null } };

export type ImpressumPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ImpressumPageFilter>;
}>;


export type ImpressumPageConnectionQuery = { __typename?: 'Query', impressumPageConnection: { __typename?: 'ImpressumPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ImpressumPageConnectionEdges', cursor: string, node?: { __typename: 'ImpressumPage', id: string, heroHeading?: string | null, heroSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'ImpressumPageSections', heading?: string | null, body?: string | null } | null> | null } | null } | null> | null } };

export type StatutenPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StatutenPageQuery = { __typename?: 'Query', statutenPage: { __typename: 'StatutenPage', id: string, heroHeading?: string | null, heroSubtext?: string | null, pdfUrl?: string | null, pdfButtonLabel?: string | null, footerNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'StatutenPageSections', heading?: string | null, body?: string | null } | null> | null } };

export type StatutenPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StatutenPageFilter>;
}>;


export type StatutenPageConnectionQuery = { __typename?: 'Query', statutenPageConnection: { __typename?: 'StatutenPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StatutenPageConnectionEdges', cursor: string, node?: { __typename: 'StatutenPage', id: string, heroHeading?: string | null, heroSubtext?: string | null, pdfUrl?: string | null, pdfButtonLabel?: string | null, footerNote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'StatutenPageSections', heading?: string | null, body?: string | null } | null> | null } | null } | null> | null } };

export type MembersDocQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MembersDocQuery = { __typename?: 'Query', membersDoc: { __typename: 'MembersDoc', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'MembersDocMembers', name?: string | null, role?: string | null, location?: string | null, links?: Array<{ __typename: 'MembersDocMembersLinks', type?: string | null, url?: string | null } | null> | null } | null> | null } };

export type MembersDocConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MembersDocFilter>;
}>;


export type MembersDocConnectionQuery = { __typename?: 'Query', membersDocConnection: { __typename?: 'MembersDocConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MembersDocConnectionEdges', cursor: string, node?: { __typename: 'MembersDoc', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'MembersDocMembers', name?: string | null, role?: string | null, location?: string | null, links?: Array<{ __typename: 'MembersDocMembersLinks', type?: string | null, url?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export const HomePagePartsFragmentDoc = gql`
    fragment HomePageParts on HomePage {
  __typename
  heroHeading
  heroSubtext
  heroCta
  featuresLabel
  featuresHeading
  featuresSubtext
  features {
    __typename
    icon
    title
    description
  }
  missionLabel
  missionHeading
  missionBody
  missionQuote
}
    `;
export const WarumPagePartsFragmentDoc = gql`
    fragment WarumPageParts on WarumPage {
  __typename
  heroBadge
  heroHeading
  heroSubtext
  benefitsLabel
  benefitsHeading
  benefits {
    __typename
    icon
    title
    description
  }
  ctaLabel
  ctaHeading
  ctaBody
  ctaButtonLabel
}
    `;
export const CrsvPagePartsFragmentDoc = gql`
    fragment CrsvPageParts on CrsvPage {
  __typename
  heroHeading
  heroSubtext
  valuesIntro
  values {
    __typename
    icon
    title
    description
  }
  legalText
}
    `;
export const KontaktPagePartsFragmentDoc = gql`
    fragment KontaktPageParts on KontaktPage {
  __typename
  heroHeading
  heroBody
}
    `;
export const DatenschutzPagePartsFragmentDoc = gql`
    fragment DatenschutzPageParts on DatenschutzPage {
  __typename
  heroHeading
  heroSubtext
  sections {
    __typename
    heading
    body
  }
}
    `;
export const ImpressumPagePartsFragmentDoc = gql`
    fragment ImpressumPageParts on ImpressumPage {
  __typename
  heroHeading
  heroSubtext
  sections {
    __typename
    heading
    body
  }
}
    `;
export const StatutenPagePartsFragmentDoc = gql`
    fragment StatutenPageParts on StatutenPage {
  __typename
  heroHeading
  heroSubtext
  pdfUrl
  pdfButtonLabel
  sections {
    __typename
    heading
    body
  }
  footerNote
}
    `;
export const MembersDocPartsFragmentDoc = gql`
    fragment MembersDocParts on MembersDoc {
  __typename
  members {
    __typename
    name
    role
    location
    links {
      __typename
      type
      url
    }
  }
}
    `;
export const HomePageDocument = gql`
    query homePage($relativePath: String!) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageParts
  }
}
    ${HomePagePartsFragmentDoc}`;
export const HomePageConnectionDocument = gql`
    query homePageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomePageFilter) {
  homePageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomePageParts
      }
    }
  }
}
    ${HomePagePartsFragmentDoc}`;
export const WarumPageDocument = gql`
    query warumPage($relativePath: String!) {
  warumPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WarumPageParts
  }
}
    ${WarumPagePartsFragmentDoc}`;
export const WarumPageConnectionDocument = gql`
    query warumPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WarumPageFilter) {
  warumPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WarumPageParts
      }
    }
  }
}
    ${WarumPagePartsFragmentDoc}`;
export const CrsvPageDocument = gql`
    query crsvPage($relativePath: String!) {
  crsvPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CrsvPageParts
  }
}
    ${CrsvPagePartsFragmentDoc}`;
export const CrsvPageConnectionDocument = gql`
    query crsvPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CrsvPageFilter) {
  crsvPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CrsvPageParts
      }
    }
  }
}
    ${CrsvPagePartsFragmentDoc}`;
export const KontaktPageDocument = gql`
    query kontaktPage($relativePath: String!) {
  kontaktPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...KontaktPageParts
  }
}
    ${KontaktPagePartsFragmentDoc}`;
export const KontaktPageConnectionDocument = gql`
    query kontaktPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: KontaktPageFilter) {
  kontaktPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...KontaktPageParts
      }
    }
  }
}
    ${KontaktPagePartsFragmentDoc}`;
export const DatenschutzPageDocument = gql`
    query datenschutzPage($relativePath: String!) {
  datenschutzPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DatenschutzPageParts
  }
}
    ${DatenschutzPagePartsFragmentDoc}`;
export const DatenschutzPageConnectionDocument = gql`
    query datenschutzPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DatenschutzPageFilter) {
  datenschutzPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DatenschutzPageParts
      }
    }
  }
}
    ${DatenschutzPagePartsFragmentDoc}`;
export const ImpressumPageDocument = gql`
    query impressumPage($relativePath: String!) {
  impressumPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ImpressumPageParts
  }
}
    ${ImpressumPagePartsFragmentDoc}`;
export const ImpressumPageConnectionDocument = gql`
    query impressumPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ImpressumPageFilter) {
  impressumPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ImpressumPageParts
      }
    }
  }
}
    ${ImpressumPagePartsFragmentDoc}`;
export const StatutenPageDocument = gql`
    query statutenPage($relativePath: String!) {
  statutenPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StatutenPageParts
  }
}
    ${StatutenPagePartsFragmentDoc}`;
export const StatutenPageConnectionDocument = gql`
    query statutenPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StatutenPageFilter) {
  statutenPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StatutenPageParts
      }
    }
  }
}
    ${StatutenPagePartsFragmentDoc}`;
export const MembersDocDocument = gql`
    query membersDoc($relativePath: String!) {
  membersDoc(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MembersDocParts
  }
}
    ${MembersDocPartsFragmentDoc}`;
export const MembersDocConnectionDocument = gql`
    query membersDocConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MembersDocFilter) {
  membersDocConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MembersDocParts
      }
    }
  }
}
    ${MembersDocPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homePage(variables: HomePageQueryVariables, options?: C): Promise<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}> {
        return requester<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}, HomePageQueryVariables>(HomePageDocument, variables, options);
      },
    homePageConnection(variables?: HomePageConnectionQueryVariables, options?: C): Promise<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}> {
        return requester<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}, HomePageConnectionQueryVariables>(HomePageConnectionDocument, variables, options);
      },
    warumPage(variables: WarumPageQueryVariables, options?: C): Promise<{data: WarumPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WarumPageQueryVariables, query: string}> {
        return requester<{data: WarumPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WarumPageQueryVariables, query: string}, WarumPageQueryVariables>(WarumPageDocument, variables, options);
      },
    warumPageConnection(variables?: WarumPageConnectionQueryVariables, options?: C): Promise<{data: WarumPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WarumPageConnectionQueryVariables, query: string}> {
        return requester<{data: WarumPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WarumPageConnectionQueryVariables, query: string}, WarumPageConnectionQueryVariables>(WarumPageConnectionDocument, variables, options);
      },
    crsvPage(variables: CrsvPageQueryVariables, options?: C): Promise<{data: CrsvPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CrsvPageQueryVariables, query: string}> {
        return requester<{data: CrsvPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CrsvPageQueryVariables, query: string}, CrsvPageQueryVariables>(CrsvPageDocument, variables, options);
      },
    crsvPageConnection(variables?: CrsvPageConnectionQueryVariables, options?: C): Promise<{data: CrsvPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CrsvPageConnectionQueryVariables, query: string}> {
        return requester<{data: CrsvPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CrsvPageConnectionQueryVariables, query: string}, CrsvPageConnectionQueryVariables>(CrsvPageConnectionDocument, variables, options);
      },
    kontaktPage(variables: KontaktPageQueryVariables, options?: C): Promise<{data: KontaktPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KontaktPageQueryVariables, query: string}> {
        return requester<{data: KontaktPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KontaktPageQueryVariables, query: string}, KontaktPageQueryVariables>(KontaktPageDocument, variables, options);
      },
    kontaktPageConnection(variables?: KontaktPageConnectionQueryVariables, options?: C): Promise<{data: KontaktPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KontaktPageConnectionQueryVariables, query: string}> {
        return requester<{data: KontaktPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: KontaktPageConnectionQueryVariables, query: string}, KontaktPageConnectionQueryVariables>(KontaktPageConnectionDocument, variables, options);
      },
    datenschutzPage(variables: DatenschutzPageQueryVariables, options?: C): Promise<{data: DatenschutzPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DatenschutzPageQueryVariables, query: string}> {
        return requester<{data: DatenschutzPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DatenschutzPageQueryVariables, query: string}, DatenschutzPageQueryVariables>(DatenschutzPageDocument, variables, options);
      },
    datenschutzPageConnection(variables?: DatenschutzPageConnectionQueryVariables, options?: C): Promise<{data: DatenschutzPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DatenschutzPageConnectionQueryVariables, query: string}> {
        return requester<{data: DatenschutzPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DatenschutzPageConnectionQueryVariables, query: string}, DatenschutzPageConnectionQueryVariables>(DatenschutzPageConnectionDocument, variables, options);
      },
    impressumPage(variables: ImpressumPageQueryVariables, options?: C): Promise<{data: ImpressumPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImpressumPageQueryVariables, query: string}> {
        return requester<{data: ImpressumPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImpressumPageQueryVariables, query: string}, ImpressumPageQueryVariables>(ImpressumPageDocument, variables, options);
      },
    impressumPageConnection(variables?: ImpressumPageConnectionQueryVariables, options?: C): Promise<{data: ImpressumPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImpressumPageConnectionQueryVariables, query: string}> {
        return requester<{data: ImpressumPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ImpressumPageConnectionQueryVariables, query: string}, ImpressumPageConnectionQueryVariables>(ImpressumPageConnectionDocument, variables, options);
      },
    statutenPage(variables: StatutenPageQueryVariables, options?: C): Promise<{data: StatutenPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatutenPageQueryVariables, query: string}> {
        return requester<{data: StatutenPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatutenPageQueryVariables, query: string}, StatutenPageQueryVariables>(StatutenPageDocument, variables, options);
      },
    statutenPageConnection(variables?: StatutenPageConnectionQueryVariables, options?: C): Promise<{data: StatutenPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatutenPageConnectionQueryVariables, query: string}> {
        return requester<{data: StatutenPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StatutenPageConnectionQueryVariables, query: string}, StatutenPageConnectionQueryVariables>(StatutenPageConnectionDocument, variables, options);
      },
    membersDoc(variables: MembersDocQueryVariables, options?: C): Promise<{data: MembersDocQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MembersDocQueryVariables, query: string}> {
        return requester<{data: MembersDocQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MembersDocQueryVariables, query: string}, MembersDocQueryVariables>(MembersDocDocument, variables, options);
      },
    membersDocConnection(variables?: MembersDocConnectionQueryVariables, options?: C): Promise<{data: MembersDocConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MembersDocConnectionQueryVariables, query: string}> {
        return requester<{data: MembersDocConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MembersDocConnectionQueryVariables, query: string}, MembersDocConnectionQueryVariables>(MembersDocConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.3/content/684bbcab-f24c-4aa8-b766-37628385f2fb/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  